#ifndef DMA_CFG_H
#define DMA_CFG_H

/* Channel memory to memory mode configuration 
	Options:
	1- MEM2MEM_DISABLED
	2- MEM2MEM_ENABLED
*/
#define CHANNEL1_MEM2MEM	MEM2MEM_DISABLED
#define CHANNEL2_MEM2MEM	MEM2MEM_DISABLED
#define CHANNEL3_MEM2MEM	MEM2MEM_DISABLED
#define CHANNEL4_MEM2MEM	MEM2MEM_DISABLED
#define CHANNEL5_MEM2MEM	MEM2MEM_DISABLED
#define CHANNEL6_MEM2MEM	MEM2MEM_DISABLED
#define CHANNEL7_MEM2MEM	MEM2MEM_DISABLED

/* Channel priority configuration 
	Options:
	1- CH_PRI_LOW
	2- CH_PRI_MEDIUM
	3- CH_PRI_HIGH
	4- CH_PRI_VERY HIGH
*/
#define CHANNEL1_PRIORITY	CH_PRI_LOW
#define CHANNEL2_PRIORITY	CH_PRI_LOW
#define CHANNEL3_PRIORITY	CH_PRI_LOW
#define CHANNEL4_PRIORITY	CH_PRI_LOW
#define CHANNEL5_PRIORITY	CH_PRI_LOW
#define CHANNEL6_PRIORITY	CH_PRI_LOW
#define CHANNEL7_PRIORITY	CH_PRI_LOW

/* Channel memory size configuration 
	Options:
	1- BITS_8	
	2- BITS_16
	3- BITS_32
*/
#define CHANNEL1_MSIZE		MSIZE_BITS_8
#define CHANNEL2_MSIZE		MSIZE_BITS_8
#define CHANNEL3_MSIZE		MSIZE_BITS_8
#define CHANNEL4_MSIZE		MSIZE_BITS_8
#define CHANNEL5_MSIZE		MSIZE_BITS_8
#define CHANNEL6_MSIZE		MSIZE_BITS_8
#define CHANNEL7_MSIZE		MSIZE_BITS_8

/* Channel memory size configuration 
	Options:
	1- BITS_8	
	2- BITS_16
	3- BITS_32
*/
#define CHANNEL1_PSIZE		PSIZE_BITS_8
#define CHANNEL2_PSIZE		PSIZE_BITS_8
#define CHANNEL3_PSIZE		PSIZE_BITS_8
#define CHANNEL4_PSIZE		PSIZE_BITS_8
#define CHANNEL5_PSIZE		PSIZE_BITS_8
#define CHANNEL6_PSIZE		PSIZE_BITS_8
#define CHANNEL7_PSIZE		PSIZE_BITS_8

/* Channel memory increment mode configuration 
	Options:
	1- MINC_DISBALED	
	2- MINC_ENABLED
*/
#define CHANNEL1_MINC		MINC_DISABLED
#define CHANNEL2_MINC		MINC_DISABLED
#define CHANNEL3_MINC		MINC_DISABLED
#define CHANNEL4_MINC		MINC_DISABLED
#define CHANNEL5_MINC		MINC_DISABLED
#define CHANNEL6_MINC		MINC_DISABLED
#define CHANNEL7_MINC		MINC_DISABLED


/* Channel peripheral increment mode configuration 
	Options:
	1- PINC_DISABLED
	2- PINC_ENABLED
*/
#define CHANNEL1_PINC		PINC_DISABLED
#define CHANNEL2_PINC		PINC_DISABLED
#define CHANNEL3_PINC		PINC_DISABLED
#define CHANNEL4_PINC		PINC_DISABLED
#define CHANNEL5_PINC		PINC_DISABLED
#define CHANNEL6_PINC		PINC_DISABLED
#define CHANNEL7_PINC		PINC_DISABLED

/* Channel circular mode configuration 
	Options:
	1- CIRC_DISABLED
	2- CIRC_ENABLED
*/
#define CHANNEL1_CIRC		CIRC_DISABLED
#define CHANNEL2_CIRC		CIRC_DISABLED
#define CHANNEL3_CIRC		CIRC_DISABLED
#define CHANNEL4_CIRC		CIRC_DISABLED
#define CHANNEL5_CIRC		CIRC_DISABLED
#define CHANNEL6_CIRC		CIRC_DISABLED
#define CHANNEL7_CIRC		CIRC_DISABLED

/* Channel data transfer direction configuration 
	Options:
	1- READ_FROM_PERIPH
	2- READ_FROM_MEM
*/
#define CHANNEL1_DIR		READ_FROM_PERIPH
#define CHANNEL2_DIR		READ_FROM_PERIPH
#define CHANNEL3_DIR		READ_FROM_PERIPH
#define CHANNEL4_DIR		READ_FROM_PERIPH
#define CHANNEL5_DIR		READ_FROM_PERIPH
#define CHANNEL6_DIR		READ_FROM_PERIPH
#define CHANNEL7_DIR		READ_FROM_PERIPH


#endif /* DMA_CFG_H */