#ifndef HSWITCH_CFG_H
#define HSWITCH_CFG_H

#define SWITCH0					SWITCH_TACKTILE0
#define SWITCH0_PORT			GPIOA
#define SWITCH0_PIN				GPIO_PIN_12
#define SWITCH0_ACTIVE_STATE	SWITCH_ACTIVE_HIGH


#define SWITCH1					SWITCH_TACKTILE1
#define SWITCH1_PORT			GPIOA
#define SWITCH1_PIN				GPIO_PIN_12
#define SWITCH1_ACTIVE_STATE	SWITCH_ACTIVE_HIGH


#endif /* HSWITCH_CFG_H */
